

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-services-security-microservices

server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
       name: Product Service
       url: /aggregate/product-service/v1/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v1/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v1/api-docs



routes:
  url:
    product-service: http://localhost:1662
    order-service: http://localhost:1663
    inventory-service: http://localhost:1664