

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-services-security-microservices

server:
  port: 9000


routes:
  url:
    product-service: http://localhost:1662
    order-service: http://localhost:1663
    inventory-service: http://localhost:1664